{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chnosz
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/CHNOSZ_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/CHNOSZ/CHNOSZ_{{ version }}.tar.gz
  sha256: 3b75a3e19a6f15a3f6e4a2bffae4de537967ba6b8a693b2eb8aae069dd358fc7

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                        # [win]


requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('CHNOSZ')"           # [not win]
    - "\"%R%\" -e \"library('CHNOSZ')\""  # [win]

about:
  home: https://www.chnosz.net/, https://r-forge.r-project.org/projects/chnosz/
  license: AGPL-3.0-only
  summary: An integrated set of tools for thermodynamic calculations in aqueous geochemistry
    and geobiochemistry. Functions are provided for writing balanced reactions to form
    species from user-selected basis species and for calculating the standard molal
    properties of species and reactions, including the standard Gibbs energy and equilibrium
    constant. Calculations of the non-equilibrium chemical affinity and equilibrium
    chemical activity of species can be portrayed on diagrams as a function of temperature,
    pressure, or activity of basis species; in two dimensions, this gives a maximum
    affinity or predominance diagram. The diagrams have formatted chemical formulas
    and axis labels, and water stability limits can be added to Eh-pH, oxygen fugacity-
    temperature, and other diagrams with a redox variable. The package has been developed
    to handle common calculations in aqueous geochemistry, such as solubility due to
    complexation of metal ions, mineral buffers of redox or pH, and changing the basis
    species across a diagram ("mosaic diagrams"). CHNOSZ also implements a group additivity
    algorithm for the standard thermodynamic properties of proteins.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
# Date: 2024-02-11

extra:
  recipe-maintainers:
    - cmkobel

# Package: CHNOSZ
# Version: 2.1.0
# Title: Thermodynamic Calculations and Diagrams for Geochemistry
# Authors@R: c( person("Jeffrey", "Dick", , "j3ffdick@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-0687-5890")) )
# Author: Jeffrey Dick [aut, cre] (<https://orcid.org/0000-0002-0687-5890>)
# Maintainer: Jeffrey Dick <j3ffdick@gmail.com>
# Depends: R (>= 3.1.0)
# Suggests: tinytest, knitr, rmarkdown, tufte
# Imports: grDevices, graphics, stats, utils
# Description: An integrated set of tools for thermodynamic calculations in aqueous geochemistry and geobiochemistry. Functions are provided for writing balanced reactions to form species from user-selected basis species and for calculating the standard molal properties of species and reactions, including the standard Gibbs energy and equilibrium constant. Calculations of the non-equilibrium chemical affinity and equilibrium chemical activity of species can be portrayed on diagrams as a function of temperature, pressure, or activity of basis species; in two dimensions, this gives a maximum affinity or predominance diagram. The diagrams have formatted chemical formulas and axis labels, and water stability limits can be added to Eh-pH, oxygen fugacity- temperature, and other diagrams with a redox variable. The package has been developed to handle common calculations in aqueous geochemistry, such as solubility due to complexation of metal ions, mineral buffers of redox or pH, and changing the basis species across a diagram ("mosaic diagrams"). CHNOSZ also implements a group additivity algorithm for the standard thermodynamic properties of proteins.
# Encoding: UTF-8
# License: GPL-3
# VignetteBuilder: knitr
# URL: https://www.chnosz.net/, https://r-forge.r-project.org/projects/chnosz/
# NeedsCompilation: yes
# Packaged: 2024-02-11 13:02:38 UTC; jedick
# Repository: CRAN
# Date/Publication: 2024-02-11 13:40:02 UTC
